
device: "cuda:0"

# Target network hyperparameters
gamma: 0.99
target_eps: !!float 0.995 # Same as SAC paper

sub_batch_size: 100

# Optimization hyperparameters
num_optim_epochs: 10
lr: !!float 3e-4 # Same as SAC paper
# lr: !!float 1e-3
max_grad_norm: 10
