
# task and env
# env:
#   name: CartPole-v1
#   task: ""
#   library: gym
#   seed: 42
#   max_episode_steps: 500

env:
  library: "toy"
  name: "ToyEnv"
  seed: 42
  n_states: 20
  shortcut_steps: 2
  return_x: 5
  return_y: 1
  big_reward: 10
  punishment: 0
  max_episode_steps: 100

# collector
collector:
  total_frames: 100_000
  init_random_frames: 0
  init_env_steps: 0
  frames_per_batch: 200 # "data batch size"
  reset_at_each_iter: False
  device: null
  env_per_collector: 1
  num_workers: 1

# replay buffer
replay_buffer:
  prb: 1 # use prioritized experience replay
  size: 1_000_000
  scratch_dir: null
  activate_constraints: 0.99

# optim
optim:
  utd_ratio: 10.0
  gamma: 0.99
  batch_size: 20 # "optim batch size"
  critic_lr: 1.0e-2
  actor_lr: 1.0e-2
  # alpha_lr: 3.0e-4 # DO NOT CHANGE
  alpha_lr: 1.0e-2 # DO NOT CHANGE
  weight_decay: 0.0
  target_update_polyak: 0.99
  # target_entropy_weight: 0.2
  target_entropy_weight: 0.01
  target_entropy: "auto"
  loss_function: l2
  # default is 0.98 but needs to be decreased for env
  # with small action space

# network
network:
  hidden_sizes: [20]
  activation: relu
  device: null

# logging
logger:
  backend: wandb
  project_name: torchrl_example_discrete_sac
  group_name: null
  exp_name: ${env.name}_DiscreteSAC
  mode: online
  eval_iter: 100
  video: False
