device: "cpu"

# Base environment configuration
n_states: 20
return_x: 2.0
return_y: 1.0
big_reward: 10.0
# punishment: 0.0
rollout_timeout: 200
constraints_active: False # No constraints in the beginning
