device: "cpu"

# How long to train
total_frames: 1000

# How many frames per batch
batch_size: 50

# Base environment configuration
n_states: 20
return_x: 2
return_y: 1
big_reward: 10
punishment: 0.0
rollout_timeout: 200

# How to switch the constraint
no_weight_fraction: 0.99
full_weight_fraction: 1.0

# Loss hyperparameters
clip_epsilon: 0.2
use_entropy: false

# Target network hyperparameters
gamma: 0.99
lmbda: 0.5

sub_batch_size: 20

# Optimization hyperparameters
num_optim_epochs: 10
lr: !!float 1e-2
max_grad_norm: 1
