
n_states: 20
return_x: 2
return_y: 1
big_reward: 10
gamma: 0.99
punishment: 0.0
device: "cpu"
num_optim_epochs: 10
buffer_size: 128
batch_size: 32
sub_batch_size: 32
max_grad_norm: 1
total_frames: 50000
rollout_timeout: 200
lr: !!float 1e-3
no_weight_fraction: 0.99
full_weight_fraction: 1.0
hidden_units: 20
target_eps: 0.99
target_entropy: 0.0
