device: "cpu"
policy_module_name: "policy_module"
qvalue_module_name: "qvalue_module"
rollout_timeout: 999999

# How long to train
train_episodes: 1000
eval_episodes: 10

# How often to log expensive metrics
expensive_log_interval: 100

# Model hyperparameters
hidden_units: 32

# Target network hyperparameters
gamma: 1

# Sampling/buffer hyperparameters
sub_batch_size: 10

# Optimization hyperparameters
# policy_lr: !!float 1e-6
policy_lr: !!float 1e-4
# qvalue_lr: !!float 1e-8
qvalue_lr: !!float 1e-4
num_optim_epochs: 20
max_policy_grad_norm: 1
max_qvalue_grad_norm: 100
