device: "cpu"
policy_module_name: "policy_module"
qvalue_module_name: "qvalue_module"
rollout_timeout: 999999

# How long to train
train_episodes: 1000
eval_episodes: 10

# Model hyperparameters
hidden_units: 8

# Target network hyperparameters
target_eps: 0.99
gamma: 1

# Sampling hyperparameters
buffer_size: 1_000
sub_batch_size: 256
# replay_alpha: 0.7
replay_alpha: 1.0
replay_beta: 0.5

# Optimization hyperparameters
policy_lr: !!float 1e-8
qvalue_lr: !!float 1e-3
num_optim_epochs: 10
max_policy_grad_norm: 1
max_qvalue_grad_norm: 10
