device: "cpu"
policy_module_name: "policy_module"
value_module_name: "value_module"
rollout_timeout: 999999

# How long to train
train_episodes: 1000
eval_episodes: 10

# How often to log expensive metrics
expensive_log_interval: 100

# Model hyperparameters
hidden_units: 32

# Target network hyperparameters
gamma: 1

# Sampling/buffer hyperparameters
# sub_batch_size: 1

# Optimization hyperparameters
lr: !!float 1e-4
num_optim_epochs: 5
max_policy_grad_norm: 10
max_value_grad_norm: 10
clip_epsilon: 0.2
use_entropy: true
entropy_coef: !!float 1e-1 # TODO: check what this is
critic_coef: 1.0
