
device: "cuda:0"

# Loss hyperparameters
target_entropy: null

# Target network hyperparameters
gamma: 0.99

buffer_size: 1_000_000 # Same as SAC paper
min_buffer_size: 1000
sub_batch_size: 100

# Optimization hyperparameters
num_optim_epochs: 10
lr: !!float 3e-4 # Same as SAC paper
max_grad_norm: 10
target_eps: !!float 0.995 # Same as SAC paper

# Replay buffer hyperparameters
alpha: 0.7 # Same as RB paper
beta: 0.5 # Same as RB paper
