
device: "cuda:0"

# How many frames per batch
batch_size: 1_000
# How long to train
total_frames: 1_000_000

# When to turn on constraints
constraint_activation: !!float 0.5

# Loss hyperparameters

# Target network hyperparameters
gamma: 0.99

sub_batch_size: 100
buffer_size: 1_000_000 # Same as SAC paper

# Optimization hyperparameters
num_optim_epochs: 10
lr: !!float 3e-4 # Same as SAC paper
max_grad_norm: 10
target_eps: !!float 0.995 # Same as SAC paper
